# Generated by Django 2.1.3 on 2019-03-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='手机号码', max_length=255)),
                ('mail', models.CharField(help_text='电子邮箱', max_length=255)),
                ('applicant_name', models.CharField(help_text='姓名', max_length=255)),
                ('passwd', models.CharField(help_text='密码', max_length=255)),
                ('register_time', models.DateTimeField(auto_now_add=True, help_text='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
