# Generated by Django 2.1.7 on 2019-03-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0003_auto_20190301_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contact_name',
            new_name='person_name',
        ),
    ]
