# Generated by Django 2.1.3 on 2019-03-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0006_auto_20190304_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducateExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='学校名称', max_length=255)),
                ('profession', models.CharField(help_text='专业', max_length=255)),
                ('record', models.CharField(help_text='学历', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
            ],
            options={
                'db_table': 'educate_experience',
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=255)),
                ('project_detail', models.CharField(help_text='项目描述', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
            ],
            options={
                'db_table': 'project_experience',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(help_text='简历名称', max_length=255)),
                ('applicant_name', models.CharField(help_text='求职者名称', max_length=255)),
                ('sex', models.CharField(help_text='性别', max_length=255)),
                ('age', models.CharField(help_text='年龄', max_length=255)),
                ('birth_place', models.CharField(help_text='出生地', max_length=255)),
                ('experience', models.CharField(help_text='工作经验', max_length=255)),
                ('phone_number', models.CharField(help_text='手机号', max_length=255)),
                ('mail', models.CharField(help_text='邮箱', max_length=255)),
                ('apply_status', models.CharField(help_text='求职状态', max_length=255)),
                ('profession', models.CharField(help_text='期望行业', max_length=255)),
                ('work_place', models.CharField(help_text='期望工作地点', max_length=255)),
                ('post_name', models.CharField(help_text='期望职位', max_length=255)),
                ('salary', models.CharField(help_text='期望薪资', max_length=255)),
                ('work_nature', models.CharField(help_text='工作性质', max_length=255)),
                ('self_judge', models.TextField(help_text='自我评价')),
                ('default_resume', models.BooleanField(default=False, help_text='默认简历')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('applicant', models.ForeignKey(help_text='所属求职者', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant')),
            ],
            options={
                'db_table': 'resume',
                'ordering': ['update_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='技能名称', max_length=255)),
                ('level', models.CharField(help_text='掌握程度', max_length=255)),
                ('use_time', models.CharField(help_text='使用时长', max_length=255)),
                ('resume', models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='公司名称', max_length=255)),
                ('post_name', models.CharField(help_text='职位名称', max_length=255)),
                ('salary', models.CharField(help_text='薪资', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
                ('work_detail', models.CharField(help_text='工作描述', max_length=255)),
                ('resume', models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['update_datetime']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_datetime',
            new_name='update_datetime',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='公司地址', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(help_text='公司类型', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_check',
            field=models.BooleanField(default=False, help_text='是否验证'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_product',
            field=models.CharField(help_text='主营产品', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='staff_number',
            field=models.CharField(help_text='员工数', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_info',
            field=models.TextField(help_text='公司简介', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='resume',
            field=models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume'),
        ),
        migrations.AddField(
            model_name='educateexperience',
            name='resume',
            field=models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume'),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.ManyToManyField(help_text='投递的简历', to='SuperY.Resume'),
        ),
    ]
