# Generated by Django 2.1.3 on 2019-03-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0008_auto_20190311_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='head_pic',
            field=models.ImageField(null=True, upload_to='applicant'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_licence',
            field=models.ImageField(help_text='营业执照', null=True, upload_to='company'),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='head_pic',
            field=models.ImageField(null=True, upload_to='resume'),
        ),
    ]
