# Generated by Django 2.1.3 on 2019-03-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='手机号码', max_length=255)),
                ('mail', models.CharField(help_text='电子邮箱', max_length=255, null=True)),
                ('person_name', models.CharField(help_text='注册人姓名', max_length=255)),
                ('passwd', models.CharField(help_text='密码', max_length=255)),
                ('head_pic', models.ImageField(null=True, upload_to='applicant')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, help_text='注册时间')),
                ('login_random', models.CharField(help_text='登陆号', max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicant',
                'ordering': ['register_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(help_text='搜索关键词', max_length=255)),
                ('search_datetime', models.DateTimeField(auto_now_add=True, help_text='搜索时间')),
                ('applicant', models.ForeignKey(help_text='搜索人', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant')),
            ],
            options={
                'db_table': 'applicant_search',
                'ordering': ['search_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='手机号码', max_length=255)),
                ('mail', models.CharField(help_text='电子邮箱', max_length=255)),
                ('person_name', models.CharField(help_text='注册人姓名', max_length=255)),
                ('passwd', models.CharField(help_text='密码', max_length=255)),
                ('business_licence', models.ImageField(help_text='营业执照', null=True, upload_to='company')),
                ('company_name', models.CharField(help_text='公司名称', max_length=255, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True, help_text='注册时间')),
                ('is_check', models.BooleanField(default=False, help_text='是否验证')),
                ('company_info', models.TextField(help_text='公司简介', null=True)),
                ('company_type', models.CharField(help_text='公司类型', max_length=255, null=True)),
                ('staff_number', models.CharField(help_text='员工数', max_length=255, null=True)),
                ('address', models.CharField(help_text='公司地址', max_length=255, null=True)),
                ('login_random', models.CharField(help_text='登陆号', max_length=255, null=True)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['register_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EducateExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='学校名称', max_length=255)),
                ('profession', models.CharField(help_text='专业', max_length=255)),
                ('record', models.CharField(help_text='学历', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
            ],
            options={
                'db_table': 'educate_experience',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(help_text='职位名称', max_length=255)),
                ('salary', models.CharField(help_text='薪资', max_length=255)),
                ('work_place', models.CharField(help_text='工作地点', max_length=255)),
                ('experience_require', models.CharField(help_text='工作经验要求', max_length=255)),
                ('graduate_require', models.CharField(help_text='毕业院校要求', max_length=255)),
                ('recruit_number', models.CharField(help_text='招聘人数', max_length=255)),
                ('post_info', models.TextField(help_text='岗位介绍')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='发布时间')),
                ('company', models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['update_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=255)),
                ('project_detail', models.CharField(help_text='项目描述', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
            ],
            options={
                'db_table': 'project_experience',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(help_text='简历名称', max_length=255, null=True)),
                ('head_pic', models.ImageField(null=True, upload_to='resume')),
                ('applicant_name', models.CharField(help_text='求职者名称', max_length=255, null=True)),
                ('sex', models.CharField(help_text='性别', max_length=255, null=True)),
                ('age', models.CharField(help_text='年龄', max_length=255, null=True)),
                ('birth_place', models.CharField(help_text='出生地', max_length=255, null=True)),
                ('experience', models.CharField(help_text='工作经验', max_length=255, null=True)),
                ('phone_number', models.CharField(help_text='手机号', max_length=255, null=True)),
                ('mail', models.CharField(help_text='邮箱', max_length=255, null=True)),
                ('apply_status', models.CharField(help_text='求职状态', max_length=255, null=True)),
                ('profession', models.CharField(help_text='期望行业', max_length=255, null=True)),
                ('work_place', models.CharField(help_text='期望工作地点', max_length=255, null=True)),
                ('post_name', models.CharField(help_text='期望职位', max_length=255, null=True)),
                ('salary', models.CharField(help_text='期望薪资', max_length=255, null=True)),
                ('work_nature', models.CharField(help_text='工作性质', max_length=255, null=True)),
                ('self_judge', models.TextField(help_text='自我评价', null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('applicant', models.OneToOneField(help_text='所属求职者', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant')),
                ('company_look', models.ManyToManyField(to='SuperY.Company')),
            ],
            options={
                'db_table': 'resume',
                'ordering': ['update_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='技能名称', max_length=255)),
                ('level', models.CharField(help_text='掌握程度', max_length=255)),
                ('use_time', models.CharField(help_text='使用时长', max_length=255)),
                ('resume', models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='标签名称', max_length=255)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='公司名称', max_length=255)),
                ('post_name', models.CharField(help_text='职位名称', max_length=255)),
                ('salary', models.CharField(help_text='薪资', max_length=255)),
                ('start_date', models.CharField(help_text='开始时间', max_length=255)),
                ('end_date', models.CharField(help_text='结束时间', max_length=255)),
                ('work_detail', models.CharField(help_text='工作描述', max_length=255)),
                ('resume', models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='resume',
            field=models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume'),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.ManyToManyField(help_text='投递的简历', to='SuperY.Resume'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='SuperY.Tag'),
        ),
        migrations.AddField(
            model_name='educateexperience',
            name='resume',
            field=models.ForeignKey(help_text='所属简历', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Resume'),
        ),
    ]
