# Generated by Django 2.1.3 on 2019-03-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['register_datetime']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['register_datetime']},
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='register_time',
            new_name='register_datetime',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='register_time',
            new_name='register_datetime',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
