# Generated by Django 2.1.3 on 2019-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_useful',
            field=models.BooleanField(default=False, help_text='是否可用'),
        ),
    ]
