# Generated by Django 2.1.3 on 2019-03-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0002_resume_is_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(help_text='搜索关键词', max_length=255)),
                ('search_datetime', models.DateTimeField(auto_now_add=True, help_text='搜索时间')),
                ('company', models.ForeignKey(help_text='搜索人', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company')),
            ],
            options={
                'db_table': 'company_search',
                'ordering': ['search_datetime'],
            },
        ),
    ]
