# Generated by Django 2.1.3 on 2019-03-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0002_auto_20190301_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mail',
            field=models.CharField(help_text='电子邮箱', max_length=255, null=True),
        ),
    ]
