# Generated by Django 2.1.3 on 2019-03-28 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0003_companysearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='head_pic',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company_look',
        ),
        migrations.AddField(
            model_name='resume',
            name='company_look',
            field=models.ForeignKey(help_text='浏览的企业', null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
    ]
