# Generated by Django 2.1.3 on 2019-03-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0004_auto_20190328_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='mail',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(help_text='手机号码', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(help_text='手机号码', max_length=255, unique=True),
        ),
    ]
