# Generated by Django 2.1.3 on 2019-03-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0005_auto_20190328_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mail',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passwd',
            field=models.CharField(help_text='密码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='person_name',
            field=models.CharField(help_text='注册人姓名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='register_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='注册时间', null=True),
        ),
        migrations.AlterField(
            model_name='applicantsearch',
            name='applicant',
            field=models.ForeignKey(help_text='搜索人', null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant'),
        ),
        migrations.AlterField(
            model_name='applicantsearch',
            name='search_word',
            field=models.CharField(help_text='搜索关键词', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='passwd',
            field=models.CharField(help_text='密码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='person_name',
            field=models.CharField(help_text='注册人姓名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companysearch',
            name='company',
            field=models.ForeignKey(help_text='搜索人', null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
        migrations.AlterField(
            model_name='companysearch',
            name='search_word',
            field=models.CharField(help_text='搜索关键词', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='applicant',
            field=models.OneToOneField(help_text='所属求职者', null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant'),
        ),
    ]
