# Generated by Django 2.1.3 on 2019-03-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0005_auto_20190303_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
    ]
