# Generated by Django 2.1.3 on 2019-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0006_auto_20190328_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='company_look',
        ),
        migrations.AddField(
            model_name='resume',
            name='company_look',
            field=models.ManyToManyField(help_text='浏览的企业', null=True, to='SuperY.Company'),
        ),
    ]
