# Generated by Django 2.1.3 on 2019-03-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0007_auto_20190328_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-register_datetime']},
        ),
        migrations.AlterModelOptions(
            name='applicantsearch',
            options={'ordering': ['-search_datetime']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-register_datetime']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-update_datetime']},
        ),
    ]
