# Generated by Django 2.1.3 on 2019-03-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0007_auto_20190305_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='head_pic',
            field=models.ImageField(null=True, upload_to='applicant/head_pic'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_licence',
            field=models.ImageField(help_text='营业执照', null=True, upload_to='company/business_licence'),
        ),
        migrations.AddField(
            model_name='resume',
            name='head_pic',
            field=models.ImageField(null=True, upload_to='resume/head_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
    ]
