# Generated by Django 2.1.3 on 2019-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0008_auto_20190329_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='graduate',
            field=models.CharField(help_text='毕业院校', max_length=255, null=True),
        ),
    ]
