# Generated by Django 2.1.3 on 2019-03-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0009_auto_20190311_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='applicant',
            field=models.OneToOneField(help_text='所属求职者', on_delete=django.db.models.deletion.CASCADE, to='SuperY.Applicant'),
        ),
    ]
