# Generated by Django 2.1.3 on 2019-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0009_auto_20190329_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='login_random',
            field=models.CharField(default='', help_text='登陆号', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passwd',
            field=models.CharField(default='', help_text='密码', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='person_name',
            field=models.CharField(default='', help_text='注册人姓名', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantsearch',
            name='search_word',
            field=models.CharField(default='', help_text='搜索关键词', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='', help_text='公司地址', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_licence',
            field=models.ImageField(default='', help_text='营业执照', upload_to='company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_info',
            field=models.TextField(default='', help_text='公司简介'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', help_text='公司名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(default='', help_text='公司类型', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='login_random',
            field=models.CharField(default='', help_text='登陆号', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='passwd',
            field=models.CharField(default='', help_text='密码', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='person_name',
            field=models.CharField(default='', help_text='注册人姓名', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='注册时间', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='staff_number',
            field=models.CharField(default='', help_text='员工数', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysearch',
            name='search_word',
            field=models.CharField(default='', help_text='搜索关键词', max_length=255),
        ),
        migrations.AlterField(
            model_name='educateexperience',
            name='end_date',
            field=models.CharField(default='', help_text='结束时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='educateexperience',
            name='profession',
            field=models.CharField(default='', help_text='专业', max_length=255),
        ),
        migrations.AlterField(
            model_name='educateexperience',
            name='record',
            field=models.CharField(default='', help_text='学历', max_length=255),
        ),
        migrations.AlterField(
            model_name='educateexperience',
            name='school_name',
            field=models.CharField(default='', help_text='学校名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='educateexperience',
            name='start_date',
            field=models.CharField(default='', help_text='开始时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience_require',
            field=models.CharField(default='', help_text='工作经验要求', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='graduate_require',
            field=models.CharField(default='', help_text='毕业院校要求', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_info',
            field=models.TextField(default='', help_text='岗位介绍'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='', help_text='职位名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='recruit_number',
            field=models.CharField(default='', help_text='招聘人数', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(default='', help_text='薪资', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_place',
            field=models.CharField(default='', help_text='工作地点', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='end_date',
            field=models.CharField(default='', help_text='结束时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='project_detail',
            field=models.CharField(default='', help_text='项目描述', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='project_name',
            field=models.CharField(default='', help_text='项目名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='start_date',
            field=models.CharField(default='', help_text='开始时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(default='', help_text='年龄', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='applicant_name',
            field=models.CharField(default='', help_text='求职者名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='apply_status',
            field=models.CharField(default='', help_text='求职状态', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_place',
            field=models.CharField(default='', help_text='出生地', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='company_look',
            field=models.ManyToManyField(help_text='浏览的企业', to='SuperY.Company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(default='', help_text='工作经验', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='graduate',
            field=models.CharField(default='', help_text='毕业院校', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mail',
            field=models.CharField(default='', help_text='邮箱', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default='', help_text='手机号', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='post_name',
            field=models.CharField(default='', help_text='期望职位', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.CharField(default='', help_text='期望薪资', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='self_judge',
            field=models.TextField(default='', help_text='自我评价'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='sex',
            field=models.CharField(default='', help_text='性别', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_nature',
            field=models.CharField(default='', help_text='工作性质', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_place',
            field=models.CharField(default='', help_text='期望工作地点', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(default='', help_text='掌握程度', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='', help_text='技能名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='use_time',
            field=models.CharField(default='', help_text='使用时长', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(default='', help_text='公司名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.CharField(default='', help_text='结束时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='post_name',
            field=models.CharField(default='', help_text='职位名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='salary',
            field=models.CharField(default='', help_text='薪资', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(default='', help_text='开始时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_detail',
            field=models.CharField(default='', help_text='工作描述', max_length=255),
        ),
    ]
