# Generated by Django 2.1.3 on 2019-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0010_auto_20190329_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(default='', help_text='期望从事行业', max_length=255),
        ),
    ]
