# Generated by Django 2.1.3 on 2019-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0011_resume_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_licence',
            field=models.ImageField(default='default.png', help_text='营业执照', upload_to='company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='head_pic',
            field=models.ImageField(default='default.png', null=True, upload_to='resume'),
        ),
    ]
