# Generated by Django 2.1.3 on 2019-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0012_auto_20190403_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_licence',
            field=models.ImageField(default='', help_text='营业执照', upload_to='company'),
        ),
    ]
