# Generated by Django 2.1.3 on 2019-04-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0013_auto_20190403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='head_pic',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='head_pic',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
