# Generated by Django 2.1.3 on 2019-04-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperY', '0014_auto_20190404_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='login_random',
        ),
        migrations.RemoveField(
            model_name='company',
            name='login_random',
        ),
    ]
